---
version: 2

build:
  os: "ubuntu-lts-latest"
  tools:
    python: "3.13"
  jobs:
    install:
      - pip install --upgrade pip
      - pip install -e . --group docs

sphinx:
  configuration: docs/conf.py
